spring.application.name=art_portfolio

# ===== DATABASE CONFIG =====
spring.datasource.url=postgresql://musefulm:iqVTKNxfzLnwbbExKRUfhprHrtKqJz3J@dpg-d7q70vhugtpc73aoth00-a/artworks_uerz
spring.datasource.username=musefulm
spring.datasource.password=iqVTKNxfzLnwbbExKRUfhprHrtKqJz3J
spring.datasource.driver-class-name=org.postgresql.Driver

# ===== JPA CONFIG =====
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Optional (safe to omit, Hibernate auto-detects)
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ===== SPRING DATA REST (if you use it) =====
spring.data.rest.base-path=/api