spring.application.name=art_portfolio

# ===== DATABASE CONFIG =====
spring.datasource.url=jdbc:postgresql://dpg-d7q70vhugtpc73aoth00-a:5432/artworks_uerz?sslmode=require
spring.datasource.username=artworks_uerz_user
spring.datasource.password=iqVTKNxfzLnwbbExKRUfhprHrtKqJz3J
spring.datasource.driver-class-name=org.postgresql.Driver

# ===== JPA CONFIG =====
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Optional (safe to omit, Hibernate auto-detects)
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ===== SPRING DATA REST (if you use it) =====
spring.data.rest.base-path=/api