spring.application.name=art_portfolio 
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://HOST:5432/artworks_uerz
spring.datasource.username=artworks_uerz_user
spring.datasource.password=wH1bElzLZazvXvG8jJklO0aCJ9BnZfUO

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.data.rest.base-path=/api

